"""Shared fixtures for the Byte test suite.

Provides automatic cleanup of test debris (data_map files, sqlite DBs,
FAISS indexes, config dirs) generated by integration-style tests.
"""

import glob
import os
import shutil
from pathlib import Path

import pytest

from byte._testing.optional_deps import FEATURE_TEST_REQUIREMENTS, missing_features

# Root of the project (one level above the tests package)
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

os.environ["BYTE_AUTO_INSTALL_OPTIONAL_DEPS"] = "0"


def pytest_ignore_collect(collection_path, config) -> object:
    del config
    normalized = str(Path(collection_path)).replace("\\", "/")
    for suffix, features in FEATURE_TEST_REQUIREMENTS.items():
        if normalized.endswith(suffix) and missing_features(*features):
            return True
    return False


def pytest_configure(config) -> None:
    config.addinivalue_line(
        "markers",
        "requires_feature(*names): skip a test when one or more optional Byte feature stacks are unavailable",
    )


def pytest_collection_modifyitems(config, items) -> None:
    del config
    for item in items:
        marker = item.get_closest_marker("requires_feature")
        if marker is None:
            continue
        missing = missing_features(*marker.args)
        if missing:
            item.add_marker(
                pytest.mark.skip(
                    reason="missing optional feature stack: " + ", ".join(missing)
                )
            )


def _cleanup_test_debris() -> None:
    """Remove files/dirs that cache tests leave behind in the project root."""
    patterns = [
        "data_map*.txt",
        "sqlite*.db",
        "faiss*.index",
        "*.index",
        "test.yaml",
        "test_new.yaml",
    ]
    dirs_to_remove = ["test-config", "test-new-config"]

    for pattern in patterns:
        for path in glob.glob(os.path.join(PROJECT_ROOT, pattern)):
            try:
                os.remove(path)
            except (PermissionError, OSError):
                pass

    for dirname in dirs_to_remove:
        dirpath = os.path.join(PROJECT_ROOT, dirname)
        if os.path.isdir(dirpath):
            shutil.rmtree(dirpath, ignore_errors=True)

    for path in glob.glob(os.path.join(PROJECT_ROOT, "tmp*")):
        if os.path.isdir(path):
            shutil.rmtree(path, ignore_errors=True)

    # Remove numeric directories (UUID-based MapDataManager leftovers)
    for entry in os.scandir(PROJECT_ROOT):
        if entry.is_dir() and entry.name[:1].isdigit():
            try:
                shutil.rmtree(entry.path, ignore_errors=True)
            except OSError:
                pass


@pytest.fixture(autouse=True)
def cleanup_test_debris() -> object:
    """Function-scoped fixture: cleanup before and after each test."""
    _cleanup_test_debris()
    yield
    _cleanup_test_debris()
