"""Public preprocessor facade."""

from byte.processor._pre_accessors import (
    all_content,
    concat_all_queries,
    get_file_bytes,
    get_file_name,
    get_image,
    get_image_question,
    get_input_image_file_name,
    get_input_str,
    get_inputs,
    get_messages_last_content,
    get_openai_moderation_input,
    get_prompt,
    last_content,
    last_content_without_prompt,
    last_content_without_template,
    nop,
    normalized_get_prompt,
    normalized_last_content,
)
from byte.processor._pre_canonicalize import canonicalize_text, normalize_text
from byte.processor._pre_context import (
    PromptDistillationResult,
    compact_text,
    compile_request_context,
    content_signature,
    distill_artifact_for_focus,
    distill_request_payload,
    extract_prompt_pieces,
    measure_request_prompt,
    stable_digest,
    summarize_artifact_payload,
    summarize_artifact_sketch,
    verify_request_faithfulness,
)

__all__ = [
    "PromptDistillationResult",
    "all_content",
    "canonicalize_text",
    "compact_text",
    "compile_request_context",
    "concat_all_queries",
    "content_signature",
    "distill_artifact_for_focus",
    "distill_request_payload",
    "extract_prompt_pieces",
    "get_file_bytes",
    "get_file_name",
    "get_image",
    "get_image_question",
    "get_input_image_file_name",
    "get_input_str",
    "get_inputs",
    "get_messages_last_content",
    "get_openai_moderation_input",
    "get_prompt",
    "last_content",
    "last_content_without_prompt",
    "last_content_without_template",
    "measure_request_prompt",
    "nop",
    "normalize_text",
    "normalized_get_prompt",
    "normalized_last_content",
    "stable_digest",
    "summarize_artifact_payload",
    "summarize_artifact_sketch",
    "verify_request_faithfulness",
]
