"""Provider capability metadata for the public adapter API."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

_SHARED_RUNTIME_CAPABILITIES = {
    "smart_model_routing": True,
    "multi_model_orchestration": True,
    "ai_memory": True,
    "unified_provider_router": True,
    "model_aliases": True,
    "fallback_routing": True,
    "retry_routing": True,
    "cost_based_routing": True,
    "health_weighted_routing": True,
    "semantic_signal_routing": True,
    "execution_verified_memory": True,
    "delta_generation": True,
    "context_compiler": True,
    "ambiguity_detection": True,
    "confidence_based_answer_shaping": True,
    "failure_memory": True,
    "patch_test_cocache": True,
    "workflow_planner": True,
    "tenant_safe_global_learning": True,
    "budget_aware_serving": True,
    "streaming_memory_recording": True,
    "streaming_verified_reuse": True,
    "distributed_vector_search": True,
    "memory_export_parquet": True,
    "memory_export_sqlite_dump": True,
    "prompt_piece_caching": True,
    "intent_slot_canonicalization": True,
    "retrieval_memoization": True,
    "workflow_reuse": True,
    "session_delta_memory": True,
    "precomputed_artifact_memory": True,
    "provider_native_prompt_cache_bridge": True,
    "adaptive_task_policies": True,
    "context_compiler_v2": True,
    "slot_aware_verification": True,
    "relevance_ranked_context_compiler": True,
    "focus_conditioned_context_distillation": True,
    "global_aux_context_budgeting": True,
    "cross_note_context_deduplication": True,
    "related_artifact_reuse": True,
    "cheap_consensus_verification": True,
    "coder_model_routing": True,
    "reasoning_model_routing": True,
    "verifier_model_routing": True,
    "context_sketches": True,
    "negative_context_memory": True,
    "counterfactual_workflow_memory": True,
    "uncertainty_conditioned_context_budget": True,
    "prompt_distillation": True,
    "prompt_module_registry": True,
    "retrieval_context_compression": True,
    "prompt_faithfulness_verification": True,
    "offline_prompt_artifacts": True,
    "embedding_batching": True,
    "learned_router": True,
    "speculative_routing": True,
    "evidence_aware_verification": True,
    "source_context_gap_detection": True,
    "strict_cache_revalidation": True,
}

_PROVIDER_CAPABILITY_MATRIX = {
    "openai": {
        "chat_completion": True,
        "text_completion": True,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": True,
        "document_inputs": True,
        "audio_inputs": True,
        "image_generation": True,
        "audio_transcription": True,
        "audio_translation": True,
        "speech_generation": True,
        "moderation": True,
    },
    "deepseek": {
        "chat_completion": True,
        "text_completion": False,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": False,
        "document_inputs": False,
        "audio_inputs": False,
        "image_generation": False,
        "audio_transcription": False,
        "audio_translation": False,
        "speech_generation": False,
        "moderation": False,
    },
    "anthropic": {
        "chat_completion": True,
        "text_completion": False,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": True,
        "document_inputs": True,
        "audio_inputs": False,
        "image_generation": False,
        "audio_transcription": False,
        "audio_translation": False,
        "speech_generation": False,
        "moderation": False,
    },
    "gemini": {
        "chat_completion": True,
        "text_completion": False,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": True,
        "document_inputs": True,
        "audio_inputs": True,
        "image_generation": True,
        "audio_transcription": True,
        "audio_translation": True,
        "speech_generation": True,
        "moderation": False,
    },
    "groq": {
        "chat_completion": True,
        "text_completion": False,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": True,
        "document_inputs": False,
        "audio_inputs": False,
        "image_generation": False,
        "audio_transcription": True,
        "audio_translation": True,
        "speech_generation": True,
        "moderation": False,
    },
    "openrouter": {
        "chat_completion": True,
        "text_completion": False,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": True,
        "document_inputs": True,
        "audio_inputs": True,
        "image_generation": True,
        "audio_transcription": False,
        "audio_translation": False,
        "speech_generation": False,
        "moderation": False,
    },
    "ollama": {
        "chat_completion": True,
        "text_completion": False,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": True,
        "document_inputs": False,
        "audio_inputs": False,
        "image_generation": False,
        "audio_transcription": False,
        "audio_translation": False,
        "speech_generation": False,
        "moderation": False,
    },
    "mistral": {
        "chat_completion": True,
        "text_completion": False,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": False,
        "document_inputs": False,
        "audio_inputs": False,
        "image_generation": False,
        "audio_transcription": False,
        "audio_translation": False,
        "speech_generation": False,
        "moderation": False,
    },
    "cohere": {
        "chat_completion": True,
        "text_completion": False,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": False,
        "document_inputs": False,
        "audio_inputs": False,
        "image_generation": False,
        "audio_transcription": False,
        "audio_translation": False,
        "speech_generation": False,
        "moderation": False,
    },
    "bedrock": {
        "chat_completion": True,
        "text_completion": False,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": False,
        "document_inputs": False,
        "audio_inputs": False,
        "image_generation": False,
        "audio_transcription": False,
        "audio_translation": False,
        "speech_generation": False,
        "moderation": False,
    },
    "llama_cpp": {
        "chat_completion": True,
        "text_completion": False,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": False,
        "document_inputs": False,
        "audio_inputs": False,
        "image_generation": False,
        "audio_transcription": False,
        "audio_translation": False,
        "speech_generation": False,
        "moderation": False,
    },
    "huggingface": {
        "chat_completion": True,
        "text_completion": True,
        "coding_tasks": True,
        "document_tasks": True,
        "vision_inputs": False,
        "document_inputs": False,
        "audio_inputs": False,
        "image_generation": False,
        "audio_transcription": False,
        "audio_translation": False,
        "speech_generation": False,
        "moderation": False,
        "h2o_generation": True,
        "byte_compression": True,
    },
}

_PROVIDER_ALIASES = {
    "deep-seek": "deepseek",
    "deep_seek": "deepseek",
    "hugging-face": "huggingface",
    "hugging_face": "huggingface",
    "hf": "huggingface",
    "llama.cpp": "llama_cpp",
    "llama-cpp": "llama_cpp",
    "llamacpp": "llama_cpp",
}


def provider_capabilities(provider: str) -> dict[str, Any]:
    """Return the adapter-surface capability map for a provider."""
    key = str(provider or "").strip().lower()
    key = _PROVIDER_ALIASES.get(key, key)
    base = _PROVIDER_CAPABILITY_MATRIX.get(key, {})
    if not base:
        return {}
    capabilities = deepcopy(base)
    capabilities.update(_SHARED_RUNTIME_CAPABILITIES)
    capabilities["provider"] = key
    capabilities["capability_scope"] = "byte_adapter_surface"
    return capabilities


def provider_capability_matrix() -> dict[str, dict[str, Any]]:
    """Return the full provider capability matrix for all built-in adapters."""
    return {provider: provider_capabilities(provider) for provider in _PROVIDER_CAPABILITY_MATRIX}


def supports_capability(provider: str, capability: str) -> bool:
    """Check whether a provider supports a named adapter-surface capability."""
    capabilities = provider_capabilities(provider)
    return bool(capabilities.get(capability, False))
