"""Public adapter API."""

from byte.adapter import _api_init as _api_init
from byte.adapter._api_init import (
    init_cache,
    init_exact_cache,
    init_hybrid_cache,
    init_normalized_cache,
    init_safe_semantic_cache,
    init_similar_cache,
    init_similar_cache_from_config,
)
from byte.adapter._api_support import (
    batch_embeddings,
    batch_rerank,
    clear_router_alias_registry,
    clear_router_runtime,
    compression_runtime_summary,
    execution_memory_summary,
    export_memory_artifact,
    export_memory_snapshot,
    get,
    import_memory_artifact,
    import_memory_snapshot,
    memory_summary,
    note_session_delta,
    policy_summary,
    preview_model_route,
    preview_workflow_plan,
    provider_capabilities,
    provider_capability_matrix,
    put,
    recall_artifact,
    recall_rerank_result,
    recall_retrieval_result,
    recall_tool_result,
    recent_interactions,
    register_router_alias,
    remember_artifact,
    remember_execution_result,
    remember_interaction,
    remember_rerank_result,
    remember_retrieval_result,
    remember_tool_result,
    remember_workflow_plan,
    research_registry_catalog,
    research_registry_overview,
    router_registry_summary,
    run_rerank,
    run_retrieval,
    run_tool,
    suggest_patch_pattern,
    supports_capability,
    workflow_plan_hint,
)

_get_eval = _api_init._get_eval
_get_model = _api_init._get_model
_get_pre_context_function = _api_init._get_pre_context_function

__all__ = [
    "batch_embeddings",
    "batch_rerank",
    "clear_router_alias_registry",
    "clear_router_runtime",
    "compression_runtime_summary",
    "execution_memory_summary",
    "export_memory_artifact",
    "export_memory_snapshot",
    "get",
    "import_memory_artifact",
    "import_memory_snapshot",
    "init_cache",
    "init_exact_cache",
    "init_hybrid_cache",
    "init_normalized_cache",
    "init_safe_semantic_cache",
    "init_similar_cache",
    "init_similar_cache_from_config",
    "memory_summary",
    "note_session_delta",
    "policy_summary",
    "preview_model_route",
    "preview_workflow_plan",
    "provider_capabilities",
    "provider_capability_matrix",
    "put",
    "recall_artifact",
    "recall_rerank_result",
    "recall_retrieval_result",
    "recall_tool_result",
    "recent_interactions",
    "register_router_alias",
    "remember_artifact",
    "remember_execution_result",
    "remember_interaction",
    "remember_rerank_result",
    "remember_retrieval_result",
    "remember_tool_result",
    "remember_workflow_plan",
    "research_registry_catalog",
    "research_registry_overview",
    "router_registry_summary",
    "run_rerank",
    "run_retrieval",
    "run_tool",
    "suggest_patch_pattern",
    "supports_capability",
    "workflow_plan_hint",
]
