"""Curated verification targets for repo-owned validation and security checks."""

from __future__ import annotations


def _unique_targets(*groups: list[str]) -> list[str]:
    ordered: list[str] = []
    seen: set[str] = set()
    for group in groups:
        for item in group:
            if item in seen:
                continue
            seen.add(item)
            ordered.append(item)
    return ordered


STRICT_TYPECHECK_TARGETS = [
    "byte/config.py",
    "byte/_config_runtime.py",
    "byte/_config_sections.py",
    "byte/core.py",
    "byte/adapter/runtime.py",
    "byte/adapter/router_runtime.py",
    "byte/adapter/_router_attempts.py",
    "byte/adapter/_router_dispatch.py",
    "byte/adapter/_router_execution.py",
    "byte/adapter/_router_registry.py",
    "byte/adapter/_router_resolution.py",
    "byte/adapter/_router_selection.py",
    "byte/adapter/pipeline/_sync_pipeline_impl.py",
    "byte/adapter/pipeline/_async_pipeline_impl.py",
    "byte/adapter/pipeline/_pipeline_bootstrap.py",
    "byte/adapter/pipeline/_pipeline_cache.py",
    "byte/adapter/pipeline/_pipeline_common.py",
    "byte/adapter/pipeline/_pipeline_finalize.py",
    "byte/adapter/pipeline/_pipeline_persist.py",
    "byte/adapter/pipeline/_pipeline_provider.py",
    "byte/adapter/pipeline/_pipeline_state.py",
    "byte_server/server.py",
    "byte_server/_server_gateway.py",
    "byte_server/_server_state.py",
    "byte_server/models.py",
    "byte_server/_server_security.py",
    "byte_server/_server_security_audit.py",
    "byte_server/_server_security_auth.py",
    "byte_server/_server_security_metrics.py",
    "byte_server/_server_security_middleware.py",
    "byte_server/_server_security_validation.py",
    "byte_server/_control_plane.py",
    "byte_server/_control_plane_routing.py",
    "byte_server/_control_plane_runtime.py",
    "byte_server/_control_plane_scope.py",
    "byte_server/telemetry.py",
]

STRICT_MYPY_MODULES = [
    "byte.config",
    "byte._config_runtime",
    "byte._config_sections",
    "byte.core",
    "byte.adapter.runtime",
    "byte.adapter.router_runtime",
    "byte.adapter._router_attempts",
    "byte.adapter._router_dispatch",
    "byte.adapter._router_execution",
    "byte.adapter._router_registry",
    "byte.adapter._router_resolution",
    "byte.adapter._router_selection",
    "byte.adapter.pipeline._sync_pipeline_impl",
    "byte.adapter.pipeline._async_pipeline_impl",
    "byte.adapter.pipeline._pipeline_bootstrap",
    "byte.adapter.pipeline._pipeline_cache",
    "byte.adapter.pipeline._pipeline_common",
    "byte.adapter.pipeline._pipeline_finalize",
    "byte.adapter.pipeline._pipeline_persist",
    "byte.adapter.pipeline._pipeline_provider",
    "byte.adapter.pipeline._pipeline_state",
    "byte_server.server",
    "byte_server._server_gateway",
    "byte_server._server_state",
    "byte_server.models",
    "byte_server._server_security",
    "byte_server._server_security_audit",
    "byte_server._server_security_auth",
    "byte_server._server_security_metrics",
    "byte_server._server_security_middleware",
    "byte_server._server_security_validation",
    "byte_server._control_plane",
    "byte_server._control_plane_routing",
    "byte_server._control_plane_runtime",
    "byte_server._control_plane_scope",
    "byte_server.telemetry",
]

BENCHMARK_SCRIPT_TARGETS = [
    "benchmark.py",
    "scripts/advanced_openai_cost_patterns.py",
    "scripts/deep_deepseek_reasoning_reuse_benchmark.py",
    "scripts/deep_deepseek_runtime_optimization_benchmark.py",
    "scripts/deep_multi_provider_routing_memory.py",
    "scripts/deep_openai_1000_request_mixed_benchmark.py",
    "scripts/deep_openai_100_request_mixed_benchmark.py",
    "scripts/deep_openai_coding_benchmark.py",
    "scripts/deep_openai_comprehensive_workload_benchmark.py",
    "scripts/deep_openai_cost_levers.py",
    "scripts/deep_openai_prompt_stress_benchmark.py",
    "scripts/deep_openai_surface_benchmark.py",
    "scripts/deep_openai_unified_router_benchmark.py",
]

BENCHMARK_PROGRAM_TARGETS = [
    "byte/benchmarking/programs",
]

BENCHMARK_ARCHITECTURE_TARGETS = [
    "byte/benchmarking/_program_entry.py",
    "byte/benchmarking/_program_execution.py",
    "byte/benchmarking/_program_models.py",
    "byte/benchmarking/workload_families",
    "byte/benchmarking/workload_generator.py",
]

CORE_HOTSPOT_TARGETS = [
    "byte/_backends/gemini.py",
    "byte/_backends/gemini_audio.py",
    "byte/_backends/gemini_chat.py",
    "byte/_backends/gemini_clients.py",
    "byte/_backends/gemini_images.py",
    "byte/_backends/gemini_messages.py",
    "byte/_backends/gemini_responses.py",
    "byte/_core_memory.py",
    "byte/_core_memory_execution.py",
    "byte/_core_memory_interactions.py",
    "byte/_core_memory_optimization.py",
    "byte/_core_memory_patterns.py",
    "byte/_core_memory_reasoning.py",
    "byte/_core_memory_snapshot.py",
    "byte/_core_memory_tools.py",
    "byte/adapter/pipeline/_response_assessment.py",
    "byte/adapter/pipeline/_response_commit.py",
    "byte/adapter/pipeline/_response_finalize.py",
    "byte/adapter/pipeline/_response_streaming.py",
    "byte/h2o/_runtime_decode.py",
    "byte/h2o/_runtime_engine.py",
    "byte/h2o/_runtime_factory.py",
    "byte/h2o/_runtime_generation.py",
    "byte/h2o/_runtime_runtime.py",
    "byte/h2o/_runtime_tokens.py",
    "byte/processor/_model_router_policy.py",
    "byte/processor/_model_router_signals.py",
    "byte/processor/_model_router_tracker.py",
    "byte/processor/_model_router_types.py",
    "byte/processor/_optimization_artifact_store.py",
    "byte/processor/_optimization_artifacts.py",
    "byte/processor/_optimization_prompt_pieces.py",
    "byte/processor/_optimization_prompt_store.py",
    "byte/processor/_optimization_public.py",
    "byte/processor/_optimization_session_store.py",
    "byte/processor/_optimization_stores.py",
    "byte/processor/_optimization_summary.py",
    "byte/processor/_optimization_text.py",
    "byte/processor/_optimization_workflow_store.py",
    "byte/processor/model_router.py",
]

CORE_HOTSPOT_TYPECHECK_TARGETS = [
    "byte/_backends/gemini.py",
    "byte/_backends/gemini_messages.py",
    "byte/_backends/gemini_responses.py",
    "byte/_core_memory.py",
    "byte/adapter/pipeline/_response_finalize.py",
    "byte/h2o/_runtime_engine.py",
    "byte/h2o/_runtime_tokens.py",
    "byte/processor/_model_router_signals.py",
    "byte/processor/_model_router_types.py",
    "byte/processor/_optimization_stores.py",
    "byte/processor/_optimization_summary.py",
    "byte/processor/model_router.py",
]

MAINTAINABILITY_TARGETS = _unique_targets(
    STRICT_TYPECHECK_TARGETS,
    BENCHMARK_ARCHITECTURE_TARGETS,
    [
        "byte/_devtools/check_annotation_contract.py",
        "byte/_devtools/check_benchmark_claims.py",
        "byte/_devtools/check_dependency_policy.py",
        "byte/_devtools/check_maintainability_contract.py",
        "byte/_devtools/check_trust_calibration.py",
        "scripts/check_annotation_contract.py",
        "scripts/check_benchmark_claims.py",
        "scripts/check_dependency_policy.py",
        "scripts/check_maintainability_contract.py",
        "scripts/check_trust_calibration.py",
    ],
)

LINT_TARGETS = _unique_targets(
    [
        "byte/adapter/api.py",
        "byte/adapter/_api_support.py",
        "byte/adapter/_api_init.py",
        "byte/adapter/_provider_wrapper.py",
        "byte/adapter/langchain_models.py",
        "byte/adapter/runtime.py",
        "byte/adapter/pipeline/sync_pipeline.py",
        "byte/adapter/pipeline/async_pipeline.py",
        "byte/config.py",
        "byte/core.py",
        "byte/h2o/runtime.py",
        "byte/manager/factory.py",
        "byte/manager/vector_data/hnswlib_store.py",
        "byte/manager/vector_data/manager.py",
        "byte/manager/vector_data/redis_vectorstore.py",
        "byte/processor/_pre_accessors.py",
        "byte/processor/optimization_memory.py",
        "byte/processor/pre.py",
        "byte/processor/quality.py",
        "byte/processor/reasoning_reuse.py",
        "byte/prompt_distillation/core.py",
        "byte_server",
        "byte/_devtools/bootstrap_dev.py",
        "byte/_devtools/check_devx_contract.py",
        "byte/_devtools/check_annotation_contract.py",
        "byte/_devtools/check_benchmark_claims.py",
        "byte/_devtools/check_dependency_policy.py",
        "byte/_devtools/check_install_parity.py",
        "byte/_devtools/check_locks.py",
        "byte/_devtools/check_maintainability_contract.py",
        "byte/_devtools/check_package_artifacts.py",
        "byte/_devtools/check_repo_hygiene.py",
        "byte/_devtools/check_trust_calibration.py",
        "byte/_devtools/compile_check.py",
        "byte/_devtools/refresh_locks.py",
        "byte/_devtools/run_coverage.py",
        "byte/_devtools/run_integration_smoke.py",
        "byte/_devtools/run_lint.py",
        "byte/_devtools/run_security_checks.py",
        "byte/_devtools/run_tox.py",
        "byte/_devtools/run_typecheck.py",
        "byte/_devtools/run_unit_tests.py",
        "byte/_devtools/run_with_repo_python.py",
        "byte/_devtools/verification_targets.py",
        "scripts/bootstrap_dev.py",
        "scripts/check_annotation_contract.py",
        "scripts/check_benchmark_claims.py",
        "scripts/check_dependency_policy.py",
        "scripts/check_devx_contract.py",
        "scripts/check_install_parity.py",
        "scripts/check_locks.py",
        "scripts/check_maintainability_contract.py",
        "scripts/check_package_artifacts.py",
        "scripts/check_repo_hygiene.py",
        "scripts/check_trust_calibration.py",
        "scripts/compile_check.py",
        "scripts/refresh_locks.py",
        "scripts/run_coverage.py",
        "scripts/run_integration_smoke.py",
        "scripts/run_lint.py",
        "scripts/run_security_checks.py",
        "scripts/run_tox.py",
        "scripts/run_typecheck.py",
        "scripts/run_unit_tests.py",
        "scripts/run_with_repo_python.py",
        "tests/unit_tests/adapter/test_api.py",
        "tests/unit_tests/adapter/test_langchain_models.py",
        "tests/unit_tests/test_architecture_hardening.py",
        "tests/unit_tests/test_bootstrap_dev.py",
        "tests/unit_tests/test_ci_workflow.py",
        "tests/unit_tests/test_core_hotspot_refactor.py",
        "tests/unit_tests/test_doctest_examples.py",
        "tests/unit_tests/test_package_artifacts.py",
        "tests/unit_tests/test_lockfiles.py",
        "tests/unit_tests/test_repo_hygiene.py",
        "tests/unit_tests/test_validation_runners.py",
        "tests/unit_tests/test_security_checks.py",
        "tests/unit_tests/test_run_with_repo_python.py",
    ],
    STRICT_TYPECHECK_TARGETS,
    BENCHMARK_ARCHITECTURE_TARGETS,
    CORE_HOTSPOT_TARGETS,
    BENCHMARK_PROGRAM_TARGETS,
    BENCHMARK_SCRIPT_TARGETS,
)

TYPECHECK_TARGETS = _unique_targets(
    [
        "byte/adapter/api.py",
        "byte/adapter/runtime.py",
        "byte/adapter/pipeline/sync_pipeline.py",
        "byte/adapter/pipeline/async_pipeline.py",
        "byte/config.py",
        "byte/core.py",
        "byte/trust/_calibration.py",
        "byte/trust/_contracts.py",
        "byte/trust/_references.py",
        "byte/trust/_risk.py",
        "byte/trust/_scoring.py",
        "byte/_devtools/bootstrap_dev.py",
        "byte/_devtools/check_annotation_contract.py",
        "byte/_devtools/check_benchmark_claims.py",
        "byte/_devtools/check_dependency_policy.py",
        "byte/_devtools/check_devx_contract.py",
        "byte/_devtools/check_install_parity.py",
        "byte/_devtools/check_locks.py",
        "byte/_devtools/check_maintainability_contract.py",
        "byte/_devtools/check_package_artifacts.py",
        "byte/_devtools/check_repo_hygiene.py",
        "byte/_devtools/check_trust_calibration.py",
        "byte/_devtools/compile_check.py",
        "byte/processor/pre.py",
        "byte/processor/optimization_memory.py",
        "byte/processor/quality.py",
        "byte/processor/reasoning_reuse.py",
        "byte/h2o/runtime.py",
        "byte/prompt_distillation/core.py",
        "byte/_devtools/refresh_locks.py",
        "byte/_devtools/run_coverage.py",
        "byte/_devtools/run_integration_smoke.py",
        "byte/_devtools/run_lint.py",
        "byte/_devtools/run_security_checks.py",
        "byte/_devtools/run_tox.py",
        "byte/_devtools/run_typecheck.py",
        "byte/_devtools/run_unit_tests.py",
        "byte/_devtools/run_with_repo_python.py",
        "byte/_devtools/verification_targets.py",
        "scripts/bootstrap_dev.py",
        "scripts/check_annotation_contract.py",
        "scripts/check_benchmark_claims.py",
        "scripts/check_dependency_policy.py",
        "scripts/check_install_parity.py",
        "scripts/check_repo_hygiene.py",
        "scripts/compile_check.py",
        "scripts/check_package_artifacts.py",
        "scripts/check_trust_calibration.py",
        "scripts/run_tox.py",
        "scripts/run_lint.py",
        "scripts/run_security_checks.py",
        "scripts/run_coverage.py",
        "scripts/run_integration_smoke.py",
        "scripts/refresh_locks.py",
        "scripts/check_locks.py",
        "scripts/check_maintainability_contract.py",
        "scripts/run_typecheck.py",
        "scripts/run_unit_tests.py",
        "scripts/run_with_repo_python.py",
    ],
    STRICT_TYPECHECK_TARGETS,
    BENCHMARK_ARCHITECTURE_TARGETS,
    CORE_HOTSPOT_TYPECHECK_TARGETS,
)

SECURITY_CODE_TARGETS = [
    "byte/adapter/api.py",
    "byte/adapter/langchain_models.py",
    "byte/adapter/runtime.py",
    "byte/h2o/runtime.py",
    "byte/mcp_gateway.py",
    "byte/manager/factory.py",
    "byte/manager/vector_data/hnswlib_store.py",
    "byte/manager/vector_data/manager.py",
    "byte/manager/vector_data/redis_vectorstore.py",
    "byte/processor/optimization_memory.py",
    "byte/processor/pre.py",
    "byte/processor/quality.py",
    "byte/processor/reasoning_reuse.py",
    "byte/prompt_distillation/core.py",
    "byte/security.py",
    "byte_server/_server_gateway.py",
    "byte_server/_server_routes_chat.py",
    "byte_server/_server_routes_proxy.py",
    "byte_server/_server_security.py",
    "byte_server/server.py",
]

SECRET_SCAN_TARGETS = [
    ".github",
    "byte",
    "byte_server",
    "scripts",
    "README.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "pyproject.toml",
    "tox.ini",
    "ruff.toml",
    ".pre-commit-config.yaml",
    "bootstrap-dev.ps1",
    "bootstrap-dev.sh",
]


__all__ = [
    "BENCHMARK_ARCHITECTURE_TARGETS",
    "BENCHMARK_PROGRAM_TARGETS",
    "BENCHMARK_SCRIPT_TARGETS",
    "CORE_HOTSPOT_TARGETS",
    "CORE_HOTSPOT_TYPECHECK_TARGETS",
    "LINT_TARGETS",
    "MAINTAINABILITY_TARGETS",
    "SECRET_SCAN_TARGETS",
    "SECURITY_CODE_TARGETS",
    "STRICT_MYPY_MODULES",
    "STRICT_TYPECHECK_TARGETS",
    "TYPECHECK_TARGETS",
]
